### ISSUE TITLE
Automate P0 use cases for Projects

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/qa-tasks#1061]
This serves as an epic to track the automation work required to automate the **`P0 use cases for Projects`**.
**Note**: Use Public API for Project related CRUD operations

**Shepherd Extensions:**
- [x] Public API Project Extensions: https://github.com/rancher/qa-tasks/issues/1155 
  - **PR**: https://github.com/rancher/shepherd/pull/15)
- [x] PR to add replica count in deployment: https://github.com/rancher/shepherd/pull/84
- [x] Wrangler context to interact with downstream clusters: https://github.com/rancher/shepherd/pull/177

**P0 Test Cases:**
- [x] **`Generic Project Test Cases:` https://github.com/rancher/qa-tasks/issues/1248**
  - [x] Project CRUD Operations - Local Cluster
  - [x] Project CRUD Operations - Downstream Cluster
  - [x] System Project
  - [x] Project Without Resource Quota
  - [x] Move Namespace from a Project to "Not in a Project"
  - [x] Move Namespace Between Projects with NO Resource quota settings
- [x] **`Project With Resource Quotas:`** https://github.com/rancher/qa-tasks/issues/1249
  - [x] Project With Resource Quota
  - [x] Resource Quota Propagation to Existing Namespaces
  - [x] Resource Quota Deletion Propagation to Existing Namespaces
  - [x] Override Resource Quota in Namespace 
  - [x] Move Namespace from a Project without Resource quota to a Project with Resource quota
  - [x] Move Namespace from a Project with Resource quota to a Project without Resource quota
  - [x] Move Namespace from a Project with Resource quota to a Project without Resource quota - Deployment transition from ReplicaFailure to Active
- [x] **`Project With Container Default Resource Limits:`** https://github.com/rancher/qa-tasks/issues/1250
  - [x] Project With Container Default Resource Limit
  - [x] Container Default Resource Limit Deletion Propagation to Existing Namespaces
  - [x] Override Container Default Resource Limit in Namespace 
- [x] **`RBAC Checks with Project:`** https://github.com/rancher/qa-tasks/issues/1251
  - [x] RBAC Check - Cluster Owner can create/delete a Project
  - [x] RBAC Check - Cluster Member can create/delete a Project
- [ ] **`Additional Checks:`**
  - [ ] Project With Resource Quota and Container Default Resource Limit

**Comment by Priyashetty17** [comment]
- [x] Waiting on [rancher/shepherd#15](https://github.com/rancher/shepherd/pull/15) to be merged.
