### ISSUE TITLE
Fix Flaky Tests - Go and Python

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1121]
The ticket covers the current flaky tests that have been diagnosed during the release testing: 

- [x] Scaling: [Fix Scaling Flaky Tests](https://github.com/rancher/qa-tasks/issues/1113)
- [x] Snapshot Restore: [Fix Snapshot Restore Flaky Tests](https://github.com/rancher/qa-tasks/issues/1111)
- [ ] Charts: [Fix Monitoring and Charts Flaky Tests](https://github.com/rancher/qa-tasks/issues/1114)
- [ ] Additional Tests - [Fix Additional Tests](https://github.com/rancher/qa-tasks/issues/1140)
- [ ] Additional Tests Long - [Fix Flaky Additional Tests Long](https://github.com/rancher/qa-tasks/issues/1141)
- [x] Additional Tests CLI - [Fix Flaky Additional Tests CLI](https://github.com/rancher/qa-tasks/issues/1154)
