### ISSUE TITLE
[EPIC] Conversion to static `Table Tests` for Provisioning + updating our go tags for Provisioning

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1132]
Below are functional areas that we will need to separate into their respective test files to ensure static test coverage:

# PSACT
- [x] `rancher-privileged` - https://github.com/rancher/qa-tasks/issues/1173
- [x] `rancher-restricted` - https://github.com/rancher/qa-tasks/issues/1173
- [x] `rancher-baseline` - https://github.com/rancher/qa-tasks/issues/1173
---
# Windows worker nodes
- [x] RKE2 Windows worker nodes - https://github.com/rancher/qa-tasks/issues/1174
---
# Snapshots
- [x] Recurring restores - https://github.com/rancher/qa-tasks/issues/1143
- [x] Replace worker nodes - https://github.com/rancher/qa-tasks/issues/1143
- [x] Retention checks - https://github.com/rancher/qa-tasks/issues/895
---
# Advanced options
- [x] Cluster agent customization - https://github.com/rancher/qa-tasks/issues/1100
- [x] Fleet agent customization - https://github.com/rancher/qa-tasks/issues/1100

**Comment by igomez06** [comment]
One addition I would like to this is tests that test windows worker nodes similar to custom clusters, that way we can include one config with a windows ami/image.

**Comment by markusewalker** [comment]
Spoke offline on this. Team 2 QA will isolate all areas in which we want to cover as part of this effort. In addition, once done, this issue will be converted into an epic with sub-issues for better tracking efforts.

**Comment by markusewalker** [comment]
All items in this epic have been addressed. Closing issue.
