### ISSUE TITLE
[EPIC] Automate recurring run failure reporting

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1146]
- [x] [KT on the Qase reporter for both recurring runs and automation testing in Jenkins](https://github.com/rancher/qa-tasks/issues/1147)
- [x] [Implement Slack reporter using go Slack API](https://github.com/rancher/qa-tasks/issues/1148)
- [ ] [Implement parser and Qase reporter for Python tests](https://github.com/rancher/qa-tasks/issues/1149)
- [x] [Improve Parser to divide automation tests in Qase by Test Suite Name](https://github.com/rancher/qa-tasks/issues/1150)
- [ ] [Tag all automation tests with team tags in Qase](https://github.com/rancher/qa-tasks/issues/1151) (may be deprecated)
- [x] [Update Parser to only report failed tests using Slack](https://github.com/rancher/qa-tasks/issues/1152)
- [x]  #1491 
- [ ] https://github.com/rancher/qa-tasks/issues/1540

**Comment by bmdepesa** [comment]
Blocked by other recurring run improvements

**Comment by bmdepesa** [comment]
Moving back to triage.
