### ISSUE TITLE
[EPIC] OS Provisioning Matrix Checks

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1181]
- [x] https://github.com/rancher/qa-tasks/issues/1279
- [ ] https://github.com/rancher/qa-tasks/issues/1185 (One click Automation)
- [ ] https://github.com/rancher/qa-tasks/issues/1184
- [x] https://github.com/rancher/qa-tasks/issues/1210
