### ISSUE TITLE
[EPIC] Update Code Coverage Pipeline

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1183]
- [ ] [Write generator script that updates the code coverage Dockerfile](https://github.com/rancher/qa-tasks/issues/1186)
- [ ] [Update Jenkinsfile to work similar to recurring runs](https://github.com/rancher/qa-tasks/issues/1187)
- [ ] [Update Jenkinsfile for building new images](https://github.com/rancher/qa-tasks/issues/1188)
