### ISSUE TITLE
[EPIC] Convert python network tests to go

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1185]
Part of the OS matrix checks is running the legacy python network tests. We should convert those to Go, using the shepherd framework.

Tests:
```
For testing Network related changes, change this to:
-k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```
- [x] test_wl - https://github.com/rancher/qa-tasks/issues/1422
- [x] test_connectivity -  https://github.com/rancher/qa-tasks/issues/1427
- [x] test_ingress - https://github.com/rancher/qa-tasks/issues/838
- [ ] test_service_discovery - https://github.com/rancher/qa-tasks/issues/1349
- [x] test_websocket - https://github.com/rancher/qa-tasks/issues/1350

**Comment by rancher-max** [comment]
@nickwsuse assigned you to the EPIC here for awareness since you currently have https://github.com/rancher/qa-tasks/issues/1349 in your Backlog and https://github.com/rancher/qa-tasks/issues/1350 in Next Up. cc @daviswill2
