### ISSUE TITLE
[EPIC] Air Gap Charts Validations

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1190]
- Combination of downstream clusters in Airgapped environment - RKE1/RKE2/K3s. Each chart needs different behavioral updates along with [the same cluster meta grabbing](https://github.com/rancher/shepherd/blob/main/extensions/clusters/clustermeta.go#L52):
  - [x] #1195
  - [ ] #1196
  - [x] #1194
  - [x] #1199
  - [x] #1198
  - [ ] #1197
  - [ ] #1193

- Deploy all charts
  - [x] Monitoring: https://github.com/rancher/qa-tasks/issues/1114
  - [x] Alerting
  - [x] Logging
  - [ ] CIS: https://github.com/rancher/rancher/pull/41981
  - [x] Istio: https://github.com/rancher/qa-tasks/issues/1114
  - [ ] Out-of-tree checks
  - [x] Vsphere: https://github.com/rancher/rancher/pull/42454

 - Checks
   - [x] #1200 ~ Significantly Lower LOE
   - [ ]  Existing P0 test cases ~ Higher LOE

- Update Airgap Testing Pipeline
   - [x] https://github.com/rancher/qa-tasks/issues/1208

**Comment by caliskanugur** [comment]
Related ticket to fix flakiness: https://github.com/rancher/qa-tasks/issues/1114

**Comment by caliskanugur** [comment]
Current checks:

- Install => Status Deployed of the chart
- Wait deployments => num of available replicas = num of desired replicas
- Wait stateful sets => num of replicas = num of ready replicas
- Wait daemon sets => num of desired = num of available

**Comment by caliskanugur** [comment]
If the existing P0 route is chosen, we will need:

1. Analyse needed images, such as the below code snippet
2. A step to find image versions corresponding to the chart versions. - We might skip this step - 
3. A logic to merge these images into a text file with the new registry prefix
4. A second pull in the bastion node for these extra images
5. In the tests, depending on environment we might need to change image prefixes

```
----------istio
istio/examples-bookinfo-details-v1:1.13.0
istio/examples-bookinfo-ratings-v1:1.13.0
istio/examples-bookinfo-reviews-v1:1.13.0
istio/examples-bookinfo-reviews-v2:1.13.0
istio/examples-bookinfo-reviews-v3:1.13.0
istio/examples-bookinfo-productpage-v1:1.13.0
----------monitoring
rancher/shell:v0.1.18
traefik:latest
```

**Comment by caliskanugur** [comment]
Charts:

- If the ticket title has `install`: We need to add new extensions that have charts cleanup and installation functions
- If the ticket title has  `different providers support`: We need to check each payload install action and create and/or follow the pattern to implement payload keys depending on the provider types - for example; [monitoring](https://github.com/rancher/shepherd/blob/main/extensions/charts/ranchermonitoring.go#L325-L336) & [logging](https://github.com/rancher/shepherd/blob/main/extensions/charts/rancherlogging.go#L188-L192) payloads that need updates.
