### ISSUE TITLE
[EPIC] Corral - Expand Third Party Support

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1201]
Currently, Corral has mainly AWS & Digital Ocean support, third-party support for the other providers happens manually in Release & Adhoc Testing. This ticket aims to expand the support to:

- [x] #1202
- [x] #1203
- [x] #1204

After these packages are added we need to make sure current provider packages are working by adding new Corral Packages similar to these [Rancher-RKE1,](https://github.com/rancherlabs/corral-packages/blob/main/packages/aws/rancher-dynamic-rke1.yaml) [Rancher-RKE2](https://github.com/rancherlabs/corral-packages/blob/main/packages/aws/rancher-dynamic-rke2.yaml), and [Rancher-K3s](https://github.com/rancherlabs/corral-packages/blob/main/packages/aws/rancher-dynamic-k3s.yaml). Standalone Packages might be another good way to check these. RKE1, RKE2, and K3s templates already exist [here](https://github.com/rancherlabs/corral-packages/tree/main/templates):

- [ ] RKE1 Template Sanity Checks on Linode, Azure, and Vsphere Templates
- [ ] RKE2 Template Sanity Checks on Linode, Azure, and Vsphere Templates
- [ ] K3s Template Sanity Checks on Linode, Azure, and Vsphere Templates

After the sanity checks, add the new packages:

- [x] #1205
- [x] #1206
- [x] #1207

For the deletions:

- [x] https://github.com/rancher/qa-tasks/issues/983

**Comment by bmdepesa** [comment]
We will not do this. @caliskanugur can you close all related tickets?
