### ISSUE TITLE
[EPIC] Identify fleet tests

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#1273]
**Tasks**
- [x] Discuss the existing test suite with the Fleet QA/Dev team.
- [x] Discuss if there are any tests integrated with Rancher.
- [x] Gain an understanding of Fleet's role within Rancher.
- [ ] Identify test cases that require automation from a Rancher perspective. (Relevant for PIT Crew)
- [ ] Implement the identified test cases.

**Comment by floatingman** [comment]
Reach out to Prabal Sharma / Fleet QA to learn about existing tests.

**Comment by caliskanugur** [comment]
We met with the fleet team, HA upgrade bits TBD for the last two points

**Comment by caliskanugur** [comment]
- Set the next meeting
- (Potentially) At least P0 backend test case Golang
- (Potentially) HA upgrade support both for this and oLDAP, tags and flags like recurring runs

**Comment by caliskanugur** [comment]
https://github.com/rancher/qa-tasks/issues/1376 Follow up after this:

- [x] https://github.com/rancher/qa-tasks/issues/1417
- [x] https://github.com/rancher/qa-tasks/issues/1418
- [ ] https://github.com/rancher/qa-tasks/issues/1419
- [ ] https://github.com/rancher/qa-tasks/issues/1420
- [ ] https://github.com/rancher/qa-tasks/issues/1421

**Comment by rancher-max** [comment]
Fleet tests have overall been identified and are in test plans within Confluence, so closing this issue.
