### ISSUE TITLE
Migrate additional tests test_rbac_wl

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/qa-tasks#1342]
**Link to Python tests**: https://github.com/rancher/rancher/blob/release/v2.9/tests/validation/tests/v3_api/test_workload.py
**Note**: Not all test cases in the test script will be migrated from Python to Go. Only the RBAC tests listed below will be migrated.

**Test Count**: 119

**test_rbac_wl** test suite contains tests to verify create/delete/list/edit of different types of workloads based on RBAC roles
- [ ] test_rbac_wl_parametarize_create[daemonSet-project-member]
- [ ] test_rbac_wl_parametarize_create[daemonSet-project-owner]
- [ ] test_rbac_wl_parametarize_create[daemonSet-read-only]
- [ ] test_rbac_wl_parametarize_create[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametarize_create[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametarize_create[statefulSet-project-member]
- [ ] test_rbac_wl_parametarize_create[statefulSet-project-owner]
- [ ] test_rbac_wl_parametarize_create[statefulSet-read-only]
- [ ] test_rbac_wl_parametarize_create[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametarize_create[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametarize_create[cronJob-project-member]
- [ ] test_rbac_wl_parametarize_create[cronJob-project-owner]
- [ ] test_rbac_wl_parametarize_create[cronJob-read-only]
- [ ] test_rbac_wl_parametarize_create[cronJob-cluster-member]
- [ ] test_rbac_wl_parametarize_create[job-cluster-owner]
- [ ] test_rbac_wl_parametarize_create[job-project-member]
- [ ] test_rbac_wl_parametarize_create[job-project-owner]
- [ ] test_rbac_wl_parametarize_create[job-read-only]
- [ ] test_rbac_wl_parametarize_create[job-cluster-member]
- [ ] test_rbac_wl_parametrize_create_negative[daemonSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_create_negative[daemonSet-project-member]
- [ ] test_rbac_wl_parametrize_create_negative[daemonSet-project-owner]
- [ ] test_rbac_wl_parametrize_create_negative[daemonSet-read-only]
- [ ] test_rbac_wl_parametrize_create_negative[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametrize_create_negative[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_create_negative[statefulSet-project-member]
- [ ] test_rbac_wl_parametrize_create_negative[statefulSet-project-owner]
- [ ] test_rbac_wl_parametrize_create_negative[statefulSet-read-only]
- [ ] test_rbac_wl_parametrize_create_negative[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametrize_create_negative[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametrize_create_negative[cronJob-project-member]
- [ ] test_rbac_wl_parametrize_create_negative[cronJob-project-owner]
- [ ] test_rbac_wl_parametrize_create_negative[cronJob-read-only]
- [ ] test_rbac_wl_parametrize_create_negative[cronJob-cluster-member]
- [ ] test_rbac_wl_parametrize_create_negative[job-cluster-owner]
- [ ] test_rbac_wl_parametrize_create_negative[job-project-member]
- [ ] test_rbac_wl_parametrize_create_negative[job-project-owner]
- [ ] test_rbac_wl_parametrize_create_negative[job-read-only]
- [ ] test_rbac_wl_parametrize_create_negative[job-cluster-member]
- [ ] test_rbac_wl_parametrize_list[daemonSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_list[daemonSet-project-member]
- [ ] test_rbac_wl_parametrize_list[daemonSet-project-owner]
- [ ] test_rbac_wl_parametrize_list[daemonSet-read-only]
- [ ] test_rbac_wl_parametrize_list[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametrize_list[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_list[statefulSet-project-member]
- [ ] test_rbac_wl_parametrize_list[statefulSet-project-owner]
- [ ] test_rbac_wl_parametrize_list[statefulSet-read-only]
- [ ] test_rbac_wl_parametrize_list[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametrize_list[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametrize_list[cronJob-project-member]
- [ ] test_rbac_wl_parametrize_list[cronJob-project-owner]
- [ ] test_rbac_wl_parametrize_list[cronJob-read-only]
- [ ] test_rbac_wl_parametrize_list[cronJob-cluster-member]
- [ ] test_rbac_wl_parametrize_list[job-cluster-owner]
- [ ] test_rbac_wl_parametrize_list[job-project-member]
- [ ] test_rbac_wl_parametrize_list[job-project-owner]
- [ ] test_rbac_wl_parametrize_list[job-read-only]
- [ ] test_rbac_wl_parametrize_list[job-cluster-member]
- [ ] test_rbac_wl_parametrize_list_negative[daemonSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_list_negative[daemonSet-project-member]
- [ ] test_rbac_wl_parametrize_list_negative[daemonSet-project-owner]
- [ ] test_rbac_wl_parametrize_list_negative[daemonSet-read-only]
- [ ] test_rbac_wl_parametrize_list_negative[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametrize_list_negative[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_list_negative[statefulSet-project-member]
- [ ] test_rbac_wl_parametrize_list_negative[statefulSet-project-owner]
- [ ] test_rbac_wl_parametrize_list_negative[statefulSet-read-only]
- [ ] test_rbac_wl_parametrize_list_negative[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametrize_list_negative[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametrize_list_negative[cronJob-project-member]
- [ ] test_rbac_wl_parametrize_list_negative[cronJob-project-owner]
- [ ] test_rbac_wl_parametrize_list_negative[cronJob-read-only]
- [ ] test_rbac_wl_parametrize_list_negative[cronJob-cluster-member]
- [ ] test_rbac_wl_parametrize_list_negative[job-cluster-owner]
- [ ] test_rbac_wl_parametrize_list_negative[job-project-member]
- [ ] test_rbac_wl_parametrize_list_negative[job-project-owner]
- [ ] test_rbac_wl_parametrize_list_negative[job-read-only]
- [ ] test_rbac_wl_parametrize_list_negative[job-cluster-member]
- [ ] test_rbac_wl_parametrize_update[daemonSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_update[daemonSet-project-member]
- [ ] test_rbac_wl_parametrize_update[daemonSet-project-owner]
- [ ] test_rbac_wl_parametrize_update[daemonSet-read-only]
- [ ] test_rbac_wl_parametrize_update[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametrize_update[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_update[statefulSet-project-member]
- [ ] test_rbac_wl_parametrize_update[statefulSet-project-owner]
- [ ] test_rbac_wl_parametrize_update[statefulSet-read-only]
- [ ] test_rbac_wl_parametrize_update[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametrize_update[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametrize_update[cronJob-project-member]
- [ ] test_rbac_wl_parametrize_update[cronJob-project-owner]
- [ ] test_rbac_wl_parametrize_update[cronJob-read-only]
- [ ] test_rbac_wl_parametrize_update[cronJob-cluster-member]
- [ ] test_rbac_wl_parametrize_update[job-cluster-owner]
- [ ] test_rbac_wl_parametrize_update[job-project-member]
- [ ] test_rbac_wl_parametrize_update[job-project-owner]
- [ ] test_rbac_wl_parametrize_update[job-read-only]
- [ ] test_rbac_wl_parametrize_update[job-cluster-member]
- [ ] test_rbac_wl_parametrize_update_negative[daemonSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_update_negative[daemonSet-project-member]
- [ ] test_rbac_wl_parametrize_update_negative[daemonSet-project-owner]
- [ ] test_rbac_wl_parametrize_update_negative[daemonSet-read-only]
- [ ] test_rbac_wl_parametrize_update_negative[daemonSet-cluster-member]
- [ ] test_rbac_wl_parametrize_update_negative[statefulSet-cluster-owner]
- [ ] test_rbac_wl_parametrize_update_negative[statefulSet-project-member]
- [ ] test_rbac_wl_parametrize_update_negative[statefulSet-project-owner]
- [ ] test_rbac_wl_parametrize_update_negative[statefulSet-read-only]
- [ ] test_rbac_wl_parametrize_update_negative[statefulSet-cluster-member]
- [ ] test_rbac_wl_parametrize_update_negative[cronJob-cluster-owner]
- [ ] test_rbac_wl_parametrize_update_negative[cronJob-project-member]
- [ ] test_rbac_wl_parametrize_update_negative[cronJob-project-owner]
- [ ] test_rbac_wl_parametrize_update_negative[cronJob-read-only]
- [ ] test_rbac_wl_parametrize_update_negative[cronJob-cluster-member]
- [ ] test_rbac_wl_parametrize_update_negative[job-cluster-owner]
- [ ] test_rbac_wl_parametrize_update_negative[job-project-member]
- [ ] test_rbac_wl_parametrize_update_negative[job-project-owner]
- [ ] test_rbac_wl_parametrize_update_negative[job-read-only]
- [ ] test_rbac_wl_parametrize_update_negative[job-cluster-member]

**Comment by Priyashetty17** [comment]
@anupama2501 Can you please confirm if this can be closed in favor of https://github.com/rancher/qa-tasks/issues/1422?

**Comment by anupama2501** [comment]
@lscalabrini01 has been working on these but afaik, rbac tests will not be covered as part of those tests.

**Comment by Priyashetty17** [comment]
Thanks for confirming, Anu. Since the following was mentioned in the epic, it was assumed that the RBAC tests, which are part of the same file, would also be covered: 
<img width="834" alt="image" src="https://github.com/user-attachments/assets/f5516eb6-ffff-4808-b514-a8daa274a420" />

**Comment by rancher-max** [comment]
Let's handle migration of these rbac tests as part of this ticket specifically. It is current in Platform team's backlog, but PIT team can help out where needed! Sorry for any confusion
