### ISSUE TITLE
[EPIC] VAI QA Testing

### ISSUE THREAD

**Issue by MSpencer87** [rancher/qa-tasks#1406]
- [x] Testing with VAI OFF https://github.com/rancher/qa-tasks/issues/1404
- [x] Testing with VAI ON https://github.com/rancher/qa-tasks/issues/1405
- [ ] Testing with VAI on LLE https://github.com/rancher/qa-tasks/issues/1501
- [ ] https://github.com/rancher/qa-tasks/issues/1410
