### ISSUE TITLE
[EPIC] Baseline Scenario for testing performance of Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#1408]
- [ ] Identify the scenario and details - https://github.com/rancher/qa-tasks/issues/1057
- [ ] Spike for identifying automation framework - https://github.com/rancher/qa-tasks/issues/1409
- [ ] Implement the framework - https://github.com/rancher/qa-tasks/issues/1413
- [ ] Run the test - https://github.com/rancher/qa-tasks/issues/1414
- [ ] Document the findings - internally and in Rancher docs.
