### ISSUE TITLE
[EPIC] Convert python workload tests to go - `test_wl`

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#1422]
Convert python workload tests to go - `test_wl`

**Comment by lscalabrini01** [comment]
I am migrating the test_wokload python test https://github.com/rancher/rancher/blob/release/v2.9/tests/validation/tests/v3_api/test_workload.py

**Comment by lscalabrini01** [comment]
- [x] test_wl_sidekick https://github.com/rancher/qa-tasks/issues/1433
- [x] test_wl_deployment https://github.com/rancher/qa-tasks/issues/1441
- [x] test_wl_statefulset https://github.com/rancher/qa-tasks/issues/1441
- [x] test_wl_daemonset https://github.com/rancher/qa-tasks/issues/1441
- [x] test_wl_cronjob https://github.com/rancher/qa-tasks/issues/1441
- [x] test_wl_upgrade https://github.com/rancher/qa-tasks/issues/1444
- [x] test_wl_pod_scale_up https://github.com/rancher/qa-tasks/issues/1445
- [x] test_wl_pod_scale_down https://github.com/rancher/qa-tasks/issues/1445
- [x] test_wl_pause_orchestration https://github.com/rancher/qa-tasks/issues/1508
- [x] test_wl_with_hostPort https://github.com/rancher/qa-tasks/issues/1576
- [x] test_wl_with_nodePort https://github.com/rancher/qa-tasks/issues/1576
- [x] test_wl_with_clusterIp https://github.com/rancher/qa-tasks/issues/1576
- [x] test_wl_with_lb https://github.com/rancher/qa-tasks/issues/1576
- [x] test_wl_with_clusterIp_scale_and_upgrade https://github.com/rancher/qa-tasks/issues/1604
- [x] test_wl_with_nodePort_scale_and_upgrade https://github.com/rancher/qa-tasks/issues/1604
- [x] test_wl_with_hostPort_scale_and_upgrade https://github.com/rancher/qa-tasks/issues/1604
- [x] test_wl_with_lb_scale_and_upgrade https://github.com/rancher/qa-tasks/issues/1604

**Comment by Priyashetty17** [comment]
@lscalabrini01 Could you please confirm if `test_rbac_wl` was migrated as part of this Epic? I noticed the tests are in [test_workload.py](https://github.com/rancher/rancher/blob/release/v2.9/tests/validation/tests/v3_api/test_workload.py), so I wanted to double-check. Thank you!

**Comment by lscalabrini01** [comment]
> @lscalabrini01 Could you please confirm if `test_rbac_wl` was migrated as part of this Epic? I noticed the tests are in [test_workload.py](https://github.com/rancher/rancher/blob/release/v2.9/tests/validation/tests/v3_api/test_workload.py), so I wanted to double-check. Thank you!

Hi @Priyashetty17, it was not, we only migrated the workload tests, we didn't migrated the rbac tests

**Comment by Priyashetty17** [comment]
Thanks for confirming, @lscalabrini01 👍 Since the following was mentioned in the comment, it was assumed that the RBAC tests, which are part of the same file, would also be covered: <img width="834" alt="image" src="https://github.com/user-attachments/assets/f5516eb6-ffff-4808-b514-a8daa274a420" />
