### ISSUE TITLE
[EPIC] Setup scale environment

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#1453]
- [x] https://github.com/rancher/qa-tasks/issues/1459
- [x] https://github.com/rancher/qa-tasks/issues/1454
- [x] https://github.com/rancher/qa-tasks/issues/1455
- [ ] https://github.com/rancher/qa-tasks/issues/1458
- [ ] https://github.com/rancher/qa-tasks/issues/1408
- [ ] https://github.com/rancher/qa-tasks/issues/352

**Comment by moio** [comment]
please add https://github.com/rancher/qa-tasks/issues/352

**Comment by rancher-max** [comment]
We want to initially use Rancher Monitoring to track metrics, but eventually may shift to StackState as it matures.
