### ISSUE TITLE
[Epic] Setup a long-living environment

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#1456]
- [ ] https://github.com/rancher/qa-tasks/issues/1453
- [x] https://github.com/rancher/qa-tasks/issues/1457
- [ ] https://github.com/rancher/qa-tasks/issues/1713

**Comment by rancher-max** [comment]
The need for this is very high now. We also need a way to generate load into this environment. The plan right now is to have a Jenkins job to do this that have scheduled runs multiple times every day to do this. We will also need to periodically upgrade this environment, so will need a way to stop the load easily while it is "in maintenance."
