### ISSUE TITLE
[MEGA EPIC] Jenkins Improvements

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1462]
- [x] https://github.com/rancher/qa-tasks/issues/47
- [x] https://github.com/rancher/qa-tasks/issues/1466
- [x] https://github.com/rancher/qa-tasks/issues/1469
- [x] https://github.com/rancher/qa-tasks/issues/26
