### ISSUE TITLE
[Epic] Setup recurring runs for Harvester

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1618]
Depends on merging harvester client and #1617 

- [ ] provisioning (rke2, k3s), permute on cni for rke2:
  * node driver
  * custom
  * imported
  * scale up/down
  * multiple clusters at once in rancher from harvester
  * drain nodes (rke2 only)
- [ ] rancher upgrade
- [ ] rbac -- TBD (working with harvester team to find out more)
- [ ] charts -- TBD (working with harvester team to find out more)

**Comment by slickwarren** [comment]
Testing the following to prepare PR: 

- [x] recurring runs jenkinsfile setup to run in vpn -- get to running state where all stages trigger correctly
- [x] ^ + individual job - get to running state where all stages trigger correctly
- [x] make sure cleanup is working on recurring runs / individual job for:
  - [x] harvester resources
  - [x] jenkins agent resources
- [ ] pulls from prime registry / helm repo
- [ ] get gluecode to work with harvester
  * requires running code that hasn't merged yet: register harvester cluster with rancher setup in order to use harvester as a provider
  * will require running 'harvester registration with rancher' as its own stage in order to provision later
- [ ] get harvester provider to provision via rancher
  * requires running code that hasn't merged yet: register harvester cluster with rancher setup in order to use harvester as a provider
  * will require running 'harvester registration with rancher' as its own stage in order to provision later
- [ ] anything else?

**Comment by slickwarren** [comment]
note; merging this will be on hold until we figure out where our codebase will live -- and when the harvester PR will be merged.

**Comment by slickwarren** [comment]
spoke with Mich about how to automate harvester deployments to tie into our automation. The current proposal is:
* grant PIT more machines from harvester lab
* learn seeder
* get access to their deployment platform (in the lab)
* either add to their jenkins or use our harvester-jenkins-agent to create the E2E job (deploy harvester, hand off to us, create rancher there, run harvester tests, teardown)

**Comment by slickwarren** [comment]
jjb PR: https://github.com/rancherlabs/jenkins-job-builder/pull/722
