### ISSUE TITLE
Enhance ease of use for Dartboard

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#1628]
- [ ] Setting up a domain that rancher sits behind
  - [ ] load balancer may be needed here
  - [ ] Certs may be needed here
- [ ] Separate module in dartboard?
- [ ] Other things?
- [ ] Allow to be used in non-airgap/proxy mode without a bastion

https://github.com/rancher/dartboard/issues/72
https://github.com/rancher/dartboard/issues/96
https://github.com/rancher/dartboard/pull/100
