### ISSUE TITLE
[EPIC] Decouple automation from specific regions / cloud infrastructure providers

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#24]
We should be able to specify any region / credentials when using AWS in our scripts.
The current defaults should remain

Context: Running tests in a region that's not us-east-2, allowing developers to use their own AWS accounts to create resources

Things to consider:
VPC
Subnet
Credentials / Access Keys
SSH keys

--- 

Current Tasks Related to This EPIC: 

- [x] #1479
- [ ] #1480
- [x] #1481

**Comment by davidnuzik** [comment]
+1

**Comment by davidnuzik** [comment]
Some ideas:

Phase 1: Could we kick this off by just setting up new private keys for jenkins in the other aws regions and have it randomly pick a region and pair with correct ssh key / api key, etc? This way us-east-2 isn't always clogged with too many instances/lb/etc in use in short term.

Phase 2: Look into other cloud infra providers later.

**Comment by bmdepesa** [comment]
@igomez06 to start analysis for this 

We first need to find where AWS account information is stored as a default either within the code or folder properties or referenced as credentials.

**Comment by caliskanugur** [comment]
From the first spike item: https://github.com/rancher/qa-tasks/issues/1479#issuecomment-2388806327.

   - [ ] Updating Jenkinsfiles, related to: https://github.com/rancher/qa-tasks/issues/1493
   - [ ] Updating test code:
     - [ ] lib dir's cloud providers related defaults; for AWS, DO and base cloud provider class
     - [ ] Above should let frequently used jobs run after the updates; f.e. `ha_create`
     - [ ] Removing hardcoded values
     - [ ] Removing other defaults within the test files and making additions to the linked second spike's solution
