### ISSUE TITLE
Test QA Checklist -- 2.5.x

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#331]
We need to complete the following no later than 1 week after dev complete using the latest RC: 
- [ ] Validate rancher installs on hosted clusters --[ tracking issue here](tbd) or we can track with nested bullets below
  - [x] GKE
  - [ ] AKS
  - [ ] EKS
- [ ] Validate full automation suite (manually validate any failures from automation)
  * number of failed tests from automation run: 
- [x] performance validations are complete
- [ ] validate TF provisioning 

- [ ] Rancher server version upgrade testing -- [ticket to track? ](tbd)
- [ ] proxy and airgap P0 checks -- [ticket to track? ](tbd)
  - [ ] validate rancher-images.txt as part of airgap 
- [ ] chart P0 checks -- [ticket to track? ](tbd)

**Comment by sowmyav27** [comment]
Closing this as the release has gone out
