### ISSUE TITLE
[EPIC] Automation tests for RKE2 provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#369]
### Day 1 operations

**Single node cluster - 1 node all roles**
- [x] EC2 node driver
- [x] Linode
- [x] Harvester
- [x] Azure
- [x] Custom cluster

**Multi node cluster - 3 etcd, 2 cp, 3 worker nodes**
- [x] EC2 node driver
- [x] Linode
- [x] Harvester
- [x] Azure
- [x] Custom cluster

**Downstream Node driver Cluster with OS - Parameterize the input AMI/User fields**
ticket: https://github.com/rancher/qa-tasks/issues/378
- [x] RHEL 8.5
- [x] SLES SP3
- [x] Rocky 8.4
- [x] OL 8.4
- [x] Ubuntu 20.04

**Downstream Custom Cluster with OS - Parameterize the input AMI/User fields**
GHH Issue: https://github.com/rancher/qa-tasks/issues/379
- [x] RHEL 8.5
- [x] SLES SP3
- [x] Rocky 8.4
- [x] OL 8.4
- [x] Ubuntu 20.04

**clusters with Network provider**
GH Issue: https://github.com/rancher/qa-tasks/issues/387
- [x] Canal
- [x] Cilium
- [x] Calico
- [x] multus,Canal
- [x] multus, Cilium
- [x] multus, Calico

**Windows RKE2 cluster deployment**
ticket: https://github.com/rancher/rancher/pull/36793
- [x] Cluster create

**Cloud provider enabled setup**
- [x] AWS EC2
- [x] Azure

**etcd snapshots**
- [x] Snapshot + restore using `etcd` - https://github.com/rancher/qa-tasks/issues/405
- [x] Snapshot + restore using `etcd + k8s version` - https://github.com/rancher/qa-tasks/issues/406
- [x] Snapshot + restore using `etcd + k8s + cluster config` option - https://github.com/rancher/qa-tasks/issues/407
- [x] S3 enabled snapshot + restore - https://github.com/rancher/qa-tasks/issues/408
- [x] Invalid S3 creds - error - https://github.com/rancher/qa-tasks/issues/408
- [x] retention count validation

**Secrets Encryption** - https://github.com/rancher/qa-tasks/issues/427
- [ ] Enable → Verify if the secrets are encrypted
- [ ] Disable secrets encryption
- [ ] Enable Custom encryption

**RBAC for**
- [x] Snapshot - https://github.com/rancher/qa-tasks/issues/410
- [x] Restore - https://github.com/rancher/qa-tasks/issues/411
- [ ] Cert rotation - https://github.com/rancher/qa-tasks/issues/409

**RKE2 hardened cluster**
- [x] Cluster deploy

### Day 2 operations 
https://github.com/rancher/qa-tasks/issues/426
- [x] Delete node driver RKE2 cluster
- [x] Delete custom RKE2 cluster
- [x] Drain before delete node driver cluster

**TF related Automation**
https://github.com/rancher/qa-tasks/issues/386

**Comment by slickwarren** [comment]
related tickets: https://github.com/rancher/qa-tasks/issues/165

**Comment by slickwarren** [comment]
@sowmyav27 can we close this? Most of it is done and tracked in separate tickets.

**Comment by markusewalker** [comment]
Closing this issue.  Secrets encryption and the RBAC cert rotation have its own ticket that are tracking efforts being made.
