### ISSUE TITLE
[EPIC] Update Jenkins config-as-code

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#47]
Refresh the Jenkins config-as-code for better disaster recovery. 

We should be able to bring up Jenkins with as few manual steps as necessary.

- [x] Update the Jenkins deployment to use the official Jenkins helm charts
- [x] Pin the Jenkins version to avoid unexpected upgrades and plugin-breaking
- [x] Ensure all Jenkins settings are config-as-code based
- [x] Move the jnlp agent to a Rancher-controlled repository
- [x] Update settings for https/certs
- [ ] ? Shared library setting -- MOVING OUT OF THIS EPIC
- [x] ? Autoscaling

---

**Current Tasks for this Epic Ticket:**
~~- [ ] https://github.com/rancher/qa-tasks/issues/1463 -- WILL NOT DO AS PART OF THIS EPIC~~  WILL BE PART OF ITS OWN  EPIC
- [x] https://github.com/rancher/qa-tasks/issues/1464
- [x] https://github.com/rancher/qa-tasks/issues/1465

**Comment by caliskanugur** [comment]
https://github.com/bmdepesa/jenkins-casc

**Comment by bmdepesa** [comment]
Moving this back to in-progress. We still need to do some work on this: 

Update plugins to the latest versions
Setup pipelines to update images on updates
Work with EIO to move to production

**Comment by bmdepesa** [comment]
Completed except for noted items.
