### ISSUE TITLE
[EPIC] Support Matrix checks Backlog

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#476]
- New OS checks
- [x] Rancher on  an AMI 
- [x] Downstream RKE1 Node driver using an AMI 
- [x] Downstream RKE1 custom cluster using an AMI 
- [x] Downstream RKE2 Node driver using an AMI 
- [x] Downstream RKE2 custom cluster using an AMI
- [x] HA on EKS/AKS/EKS --> _Done_
