### ISSUE TITLE
Hosted/Tenant Rancher Automation

### ISSUE THREAD

**Issue by brudnak** [rancher/qa-tasks#507]
Using Terraform, Go, and Terratest to create automation for creating a hosted/tenant Rancher setup and automating P0 use cases.

- [x] ✅ Terrafrom the creates k3s infrastructure in AWS
- [x] ✅ Go/Terratest that installs k3s on the servers: https://github.com/rancher/qa-tasks/issues/508
- [x] ✅ Terratest to install Rancher on the host server: https://github.com/rancher/qa-tasks/issues/511
- [x] ✅ Terratest/Go to call Rancher API to grab admin api token to use as a building block for the next dynamically created terraform file: https://github.com/rancher/qa-tasks/issues/524
- [x] ✅ 🟦 `[unblocked now & complete]`  Terraform to create an imported cluster in the host and generate the import kubectl apply command: https://github.com/rancher/qa-tasks/issues/526
- [x] ✅ 🟦 `[unblocked now & complete]` Terratest to import the tenant k3s cluster into the host: https://github.com/rancher/qa-tasks/issues/512
- [x] ✅ Terraform to install Rancher on the tenant cluster after it's imported into the host: https://github.com/rancher/qa-tasks/issues/525
- `not applicable` ~~Terratest to create users, auth providers, install monitoring, launch downstream clusters~~
  - The above bullet point can be tested via the new Go framework with tests that have already been created
- [x] rancher/qa-tasks#615
- [x] rancher/qa-tasks#616

## Task to create a temporary work around func for the blocked issue

- [x] ✅ temporary func / workaround to create a generic imported cluster with install commands generated  https://github.com/rancher/qa-tasks/issues/546

<strike>

## After Standalone MVP in Own Repo - Integrate into Rancher Repository

- rancher/qa-tasks#623
- rancher/qa-tasks#624
- rancher/qa-tasks#625

 </strike>

**Comment by brudnak** [comment]
Initial work completed with Go, Terratet, go-rod, and Terraform. Setting up Rancher and infra for a hosted / tenant setup. Remaining 3 bullet points should maybe be added to the go framework

**Comment by brudnak** [comment]
Finished the hosted / tenant Rancher setup automation. Includes upgrading the host and tenant as well.

https://github.com/brudnak/hosted-tenant-rancher

Crossed off one bullet one above: `Terratest to create users, auth providers, install monitoring, launch downstream clusters`

As these Host/Tenant Rancher URLs can be passed to what's already been created with the Go framework tests.

**Comment by sowmyav27** [comment]
Works as a standalone repo.

Needs work to go into rancher/rancher repo. Might want to get this done using Coral.
