### ISSUE TITLE
Automate introducing new k8s in Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#708]
- [ ] Imported AKS/EKS/GKE
- [ ] Canal + PNI enabled with RKE1 and downstream cluster - Cluster provisioning _only_
- [ ] Local cluster rke1/rke2/k3s ha upgrade process 
- [ ] RKE checks
```
- Default k8s version in 1.4.5 RKE RC should be 1.26
- dev-v2.7 KDM should have the default as v1.26
```
- [ ] Cattle-cluster-agent / node-agent checks for panics in logs
- [ ] Backup restore on RKE2 with S3 enabled 
- [ ] Kubeconfig file download workflow
- [ ] Downstream Azure cloud provider RKE2 cluster 
- [ ] Downstream AWS cloud provider enabled RKE2 cluster 
- [ ] Windows vsphere node driver provisioning
- [ ] Feature charts - _tbd_
