### ISSUE TITLE
Enhance upgrade release test coverage

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#712]
This is a parent ticket to follow improvements that can be used in upgrade release tests.

- [x] VSphere Linux Support
- [ ] VSphere Windows Support https://github.com/rancher/qa-tasks/issues/523
- [ ] Imported Rancher Clusters Provisioning Support https://github.com/rancher/qa-tasks/issues/620
- [ ] Imported Hosted Clusters Provisioning Support
- [ ] Charts RKE2, K3s Support
- [x] EKS Updates https://github.com/rancher/rancher/pull/41392
- [ ] Jobs Separation to Watch Sub-Jobs https://github.com/rancher/qa-tasks/issues/675
- [ ] Windows Configuration Files Generate Support
- [x] Volume Type Options Minor Patch Support
- [ ] Add an ignore error state for the security cosmetic issue
- [ ] Update nodes list v3 to v1 nodes list and its filter in the workload tests

**Comment by caliskanugur** [comment]
Also related with this: https://github.com/rancher/qa-tasks/issues/969
