### ISSUE TITLE
[UI] GLOBAL APPS: Continuous Delivery page

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#737]
I've turned this into an epic ticket to track the following: 

- [x] dashboard: https://github.com/rancher/qa-tasks/issues/1360
- [x] git repos: https://github.com/rancher/qa-tasks/issues/1361
- [x] clusters: https://github.com/rancher/qa-tasks/issues/1359
 - [x] add coverage for https://github.com/rancher/dashboard/issues/11434

- [x] cluster groups: https://github.com/rancher/qa-tasks/issues/1362
- [x] advanced: https://github.com/rancher/qa-tasks/issues/1363

**Comment by izaac** [comment]
I think the GitRepos checkbox can be marked as done, there are currently gitrepos tests in the framework

**Comment by yonasberhe23** [comment]
Closing this epic as all tasks are complete (1 pending review)
