### ISSUE TITLE
[UI] [EPIC] Cluster Provisioning: Provision Hosted cluster - AKS/EKS/GKE

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#750]
- [x] [[UI] Cluster Provisioning - Provision Hosted Cluster - AKS #1570](https://github.com/rancher/qa-tasks/issues/1570)

- [x] [[UI] Cluster Provisioning - Provision Hosted Cluster - GKE #1571](https://github.com/rancher/qa-tasks/issues/1571)

- [x] [[UI] Cluster Provisioning - Provision Hosted Cluster - EKS #1572](https://github.com/rancher/qa-tasks/issues/1572)

**Comment by yonasberhe23** [comment]
holding off on this as the Highlander team may have automation coverage for this already

**Comment by izaac** [comment]
It's not clear if this was done by other team according to @yonasberhe23 cc @bmdepesa
