### ISSUE TITLE
[EPIC] Automate Deleting clusters and add/delete nodes from Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#771]
# Delete Clusters
- [x] Delete RKE2 clusters - https://github.com/rancher/qa-tasks/issues/769
- [x] Delete K3s clusters - https://github.com/rancher/qa-tasks/issues/669
---
# Delete/Add Nodes
- [x] Add a validation for a daemonset workload that scales appropriately with the number of worker nodes in a cluster
- [x] Delete init node in a downstream cluster - https://github.com/rancher/qa-tasks/issues/1039
## Custom Clusters
- [x] Delete and Add nodes in custom RKE2/K3S cluster - https://github.com/rancher/qa-tasks/issues/459
### K3s clusters
- [x] Add/Delete nodes in Node driver cluster
- - [x] Worker nodes - https://github.com/rancher/qa-tasks/issues/552
- - [x] Control plane nodes - 
- - [x] etcd nodes - https://github.com/rancher/qa-tasks/issues/660
- [x] Scale Down nodes in Node Driver cluster
- - [x] Worker nodes - https://github.com/rancher/qa-tasks/issues/552
- - [x] Control plane nodes
- - [x] Etcd nodes
- [x] Force Delete option on the nodes - https://github.com/rancher/qa-tasks/issues/773
### RKE2 clusters 
- [x] Add/Delete nodes in Node driver cluster - https://github.com/rancher/qa-tasks/issues/792
- [x] Scale Down nodes in Node Driver cluster - https://github.com/rancher/qa-tasks/issues/792
- [x] Scale up/down node pools - https://github.com/rancher/qa-tasks/issues/792
- [x] Force delete nodes - https://github.com/rancher/qa-tasks/issues/773

**Comment by bmdepesa** [comment]
After @markusewalker's PR is merged we want to update this issue to see what remains to be covered from the use cases in this issue.

**Comment by markusewalker** [comment]
Initial PRs for adding deleting cluster/scaling machinepools support has been merged. I updated the tasks that have been addressed as a result.

**Comment by markusewalker** [comment]
2.7 & 2.8 PRs are now up for QA task https://github.com/rancher/qa-tasks/issues/459.

**Comment by markusewalker** [comment]
Update: @Josh-Diamond has a PR up for https://github.com/rancher/qa-tasks/issues/1039. Once that is merged, we will work towards adding/deleting nodes.

**Comment by markusewalker** [comment]
https://github.com/rancher/qa-tasks/issues/1039 has PRs up and just needs to get merged. I'll close this epic as the items have been completed.
