### ISSUE TITLE
Security Testing - Research and identifying testcases to automate

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#810]
- [x] Review older CVE issues and identify security testing involved and document this
- [x] Investigate what other types of security testing can the team do. Can something be automated? 
- [ ] Automate these testcases - https://github.com/rancher/qa-tasks/issues/1078
