### ISSUE TITLE
Epic - Link Automated Tests to Qase

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#815]
- [ ] Document how to link tests to Qase for Python & Go
- [ ] Link Go tests
- [ ] Link Python tests

**Comment by bmdepesa** [comment]
Investigate what our options are for linking tests to Qase
  - Test linking individual test cases (not previously existing in Qase)
  - Test linking from test run results (file) 
  - How do we handle duplicate test cases that might get created
  - Can we link an automated case to an existing manual case?

Once we determine the best approach
  - Document whatever steps may be needed by someone writing new automation
  - Link existing Go tests (priority)
  - Link existing Python tests

https://developers.qase.io/reference/introduction-to-the-qase-api
https://docs.qase.io/documentation/general/webhooks
https://docs.qase.io/documentation/apps/ci-cd

**Comment by bmdepesa** [comment]
Go test linking is in review - still need Python & Documentation
