### ISSUE TITLE
Epic - Move Go Framework to its own repo 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#816]
Move the Go framework into it's own repo 

- [ ] Create the repo 
- [ ] Move the framework into the repo
- [ ] Update Rancher tests to import the framework from the new location
- [ ] Coordinate with other teams using the framework so their tests don't break

**Comment by igomez06** [comment]
1. Get repo created issue: https://github.com/rancherlabs/eio/issues/1755
