### ISSUE TITLE
Epic - Add the ability to create Rancher HA installations using an nginx load balancer instead of AWS

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#819]
Add the ability to create any type of Rancher HA installation using an nginx load balancer

- [ ] Corral for the nginx machine? 
- [ ] Rancher self signed
- [ ] BYO valid certs
- [ ] BYO self-signed certs
- [ ] LetsEncrypt certs

We previously have this task and associated PR for doing this through Python, but we should aim to update this to work from the Go framework - rancher/qa-tasks#15

**Comment by bmdepesa** [comment]
#206 relates to this
