### ISSUE TITLE
Performance checks for 2.7.6

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#852]
Specific release checks for next 2.7.6 release. Environments should have some measurable amount of load (60-70% of resource usage, communication between workers and control-plane nodes). 

 
- [x] [Pre-upgrade perform a soak test on local and downstream clusters](https://github.com/rancher/qa-tasks/issues/847)
- [x] [Upgrade Rancher and monitor performance for a few days post-upgrade](https://github.com/rancher/qa-tasks/issues/848) 
- [x] Post-upgrade perform the soak test again
- [x] [Upgrade long-living environments to 2.7.x and monitor for a few days post upgrade](https://github.com/rancher/qa-tasks/issues/866)
- [x] [Run object-counting scripts periodically pre and post-upgrade](https://github.com/rancher/qa-tasks/issues/853)

**Comment by MSpencer87** [comment]
## Individual Cluster Performance
### Rancher Cluster Config:
- Rancher version: latest 2.7.6-rc2
- Rancher cluster type: RKE1 HA  (3 all-roles nodes, 1 worker node tainted to run rancher-monitoring)
- Cluster Size: Medium
- Docker version: 20.10
- K8s version: v1.26.4-rancher2-1
- Log level: debug
- certmanager version: 1.11.1

### Downstream Cluster Config:
Downstream cluster types: (3 workers, 1 etcd, 1 control plane)
	- RKE1 Node Driver
	- RKE1 Custom Cluster
	- RKE2 Node Driver
	- RKE2 Custom Cluster
	- K3s Node Driver
	- K3s Custom Cluster
Installed apps: rancher-monitoring
Deployments: `helm-foldingathome`
rke1 version = v1.26.7-rancher2-1 (default)
rke2 version = v1.26.7+rke2r1 (default)
k3s version = v1.26.7+k3s1


### Method:

1. Setup HA Local (v1.26.4-rancher2-1) cluster with Rancher 2.7.5
	1. Install rancher-monitoring chart from Rancher catalog
2. Provision HA Downstreams clusters:
	- RKE1 Node Driver
	- RKE1 Custom
	- RKE2 Node Driver
	- RKE2 Custom
	- K3s Node Driver
	- K3s Custom
3. Load each downstream cluster with a set of "bulk components"
	1. 100 secrets
	2. 10 projects
	3. 12 namespaces
	4. 300 users (users are created in the Local cluster)
	5. 1 project Role Template
	6. 300 project Role Template bindings
4. Deploy `rancher-monitoring` and `helm-foldingathome` to each downstream cluster
	1. Install `rancher-monitoring` chart from Rancher catalog
	2. Add chart repo for `helm-foldingathome`
	3. Install `helm-foldingathome`
5. Run parallel soak test and object count script on a schedule, every X minutes
    - This collects resource counts > performs a soak test by loading the nodes with a # of pods and querying them repeatedly > collect resource counts again
    - The typical schedule is every 40 minutes, assuming the minimum soak period of 30 minutes
6. Collect Grafana and Prometheus metrics for each cluster
7. Complete rancher upgrade to latest rc (2.7.6-rc2)
8. Run parallel soak test and object count script on a schedule, every X minutes
    - This collects resource counts > performs a soak test by loading the nodes with a # of pods and querying them repeatedly > collect resource counts again
    - The typical schedule is every 40 minutes, assuming the minimum soak period of 30 minutes
9. Collect Grafana and Prometheus metrics for each cluster

### Results: 
- Overall stability observed throughout test scenario
	- Expected resource spikes surrouning provisioing, relevant deployments and upgrade
	- Post upgrade, the performance debug metrics stopped reporting
	- Cluster resource counts do not reflect any significant, unexpected increase or decrease
- During this performance check the soak test script was not working 100% correctly. The script has been fixed after the 2.7.7 performance checks. Here is a summary of what was non-functional: 
	- Pods scheduled on the etcd nodes were unable to become Active due to a NoExecute taint. This causes the soak test to hang for up to 30 minutes before ending
	- The duration of each soak period needs to be finetuned and was on a schedule to trigger the soak for ~30 minutes every 45 minutes
	- The soak test script is meant to load each node in a given cluster with pods + a Service that maps to them. It is then meant to run a # of queries on each pod (with a cap on in-flight queries), however this part of the script was not reachable so no queries were made
	- The above points effectively means that the script simply created a # of Pods mapped to a Service and left those pods running for ~30 minutes

Pre-Upgrade:
![local-rke1-rancher-metrics](https://github.com/rancher/qa-tasks/assets/6477538/0df0aed2-7b2f-4146-9434-18bc7e941ae8)
![local-rke1-api-server-metrics](https://github.com/rancher/qa-tasks/assets/6477538/06e86ca5-5382-4627-896e-602efe9141cf)
![local-rke1-perf-metrics1](https://github.com/rancher/qa-tasks/assets/6477538/673926ac-dd1a-4ce9-b171-7ad07ccf1009)
![local-rke1-perf-metrics2](https://github.com/rancher/qa-tasks/assets/6477538/d524dbe2-1948-4558-8b1a-a3e47c9253be)
![local-rke1-perf-metrics3](https://github.com/rancher/qa-tasks/assets/6477538/bc36b98b-febb-4b07-a94b-137dfb569339)

Post-Upgrade:
![local-rke1-rancher-metrics](https://github.com/rancher/qa-tasks/assets/6477538/25e18c02-f9c9-44a0-8ecf-746f65d62b55)
![local-rke1-api-server-metrics](https://github.com/rancher/qa-tasks/assets/6477538/4a56e9bc-0937-40e5-a0f5-b64ba5d19e47)
![local-rke1-perf-metrics1](https://github.com/rancher/qa-tasks/assets/6477538/685c30c2-0d15-4cfa-9625-160245f3fd57)
![local-rke1-perf-metrics2](https://github.com/rancher/qa-tasks/assets/6477538/28f91797-5269-4eb9-a8e2-2c794dc7b34c)
![local-rke1-perf-metrics3](https://github.com/rancher/qa-tasks/assets/6477538/0a8a3a0e-608b-4238-a8de-216ed57a7b08)
![local-rke1-prom-409s-metrics](https://github.com/rancher/qa-tasks/assets/6477538/8d3b348e-dde0-4735-9d95-b299a0767137)
![local-rke1-prom-requests-metrics](https://github.com/rancher/qa-tasks/assets/6477538/30be3dcf-f73d-4350-887f-f145e2ab09cf)

[2.7.6-perf-artifacts.zip](https://github.com/rancher/qa-tasks/files/12588598/2.7.6-perf-artifacts.zip)
