### ISSUE TITLE
Performance checks for 2.7.7

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#880]
Specific release checks for the v2.7.7 release. Environments should have some measurable amount of load (60-70% of resource usage, communication between workers and control-plane nodes). 

 
- [x] [Pre-upgrade perform a soak test on local and downstream clusters](https://github.com/rancher/qa-tasks/issues/847)
- [x] [Upgrade Rancher and monitor performance for a few days post-upgrade](https://github.com/rancher/qa-tasks/issues/848) 
- [x] Post-upgrade perform the soak test again
- [x] [Upgrade long-living environments to 2.7.7 and monitor for a few days post upgrade](https://github.com/rancher/qa-tasks/issues/866)
- [x] [Run object-counting scripts periodically pre and post-upgrade](https://github.com/rancher/qa-tasks/issues/853)

**Comment by git-ival** [comment]
### Rancher Cluster Config:
Rancher version: latest 2.7.6-rc2
Rancher cluster type: RKE1 HA  (3 all-roles nodes, 1 worker node tainted to run rancher-monitoring)
Cluster Size: Medium
Docker version: 20.10
K8s version: v1.26.4-rancher2-1
Log level: debug
certmanager version: 1.11.1

### Downstream Cluster Config:
Downstream cluster types: (3 workers, 1 etcd, 1 control plane)
- RKE1 Node Driver
- RKE1 Custom Cluster
- RKE2 Node Driver
- RKE2 Custom Cluster
- K3s Node Driver
- K3s Custom Cluster
Installed apps: `rancher-monitoring`
Deployments: `helm-foldingathome`
rke1 version = v1.26.7-rancher2-1 (default)
rke2 version = v1.26.7+rke2r1 (default)
k3s version = v1.26.7+k3s1 

### Method:
1. Setup HA Local (k8s version) cluster with Rancher 2.7.6-rc2
	1. Install rancher-monitoring chart from Rancher catalog
2. Create HA Downstream clusters:
	- RKE1 Node Driver
	- RKE1 Custom
	- RKE2 Node Driver
	- RKE2 Custom
	- K3s Node Driver
	- K3s Custom
3. Load each downstream cluster with a set of "bulk components"
	1. 100 secrets
	2. 10 projects
	3. 12 namespaces
	4. 300 users (users are created in the Local cluster)
	5. 1 project Role Template
	6. 300 project Role Template bindings
4. Deploy `rancher-monitoring` and `helm-foldingathome` to each downstream cluster
	1. Install `rancher-monitoring` chart from Rancher catalog
	2. Add chart repo for `helm-foldingathome`
	3. Install `helm-foldingathome`
	4. Finetune the # of replicas for each individual cluster so that the total CPU usage hovers around ~70%
5. Run parallel soak test and object count script on a schedule, every X minutes
    - This collects resource counts > performs a soak test by loading the nodes with a # of pods and querying them repeatedly > collect resource counts again
    - The typical schedule is every 40 minutes, assuming the minimum soak period of 30 minutes
6. Collect Grafana and Prometheus metrics for each cluster
7. Complete rancher upgrade to latest rc (2.7.7-rc4)
8. Run parallel soak test and object count script on a schedule, every X minutes
    - This collects resource counts > performs a soak test by loading the nodes with a # of pods and querying them repeatedly > collect resource counts again
    - The typical schedule is every 40 minutes, assuming the minimum soak period of 30 minutes
9. Collect Grafana and Prometheus metrics for each cluster

### Observations:
- During this performance check the soak test script was not working 100% correctly. The script has been fixed for future performance checks. Here is a summary of what was non-functional: 
	- Pods scheduled on the etcd nodes were unable to become Active due to a NoExecute taint. This causes the soak test to hang for up to 30 minutes before ending
	- The duration of each soak period needs to be finetuned and was on a schedule to trigger the soak for ~30 minutes every 45 minutes
	- The soak test script is meant to load each node in a given cluster with pods + a Service that maps to them. It is then meant to run a # of queries on each pod (with a cap on in-flight queries), however this part of the script was not reachable so no queries were made
	- The above points effectively means that the script simply created a # of Pods mapped to a Service and left those pods running for ~30 minutes
- Overall spikes in resource usage align with periods where downstreams were being loaded up with "objects" and when soak tests/object counts were being collected
	- Additionally, smaller and more frequent spikes can be seen which align with the foldingathome workloads
	- Disk Utilization is noticeably higher than observed during the 2.7.6 perf checks by about 5-8%
	- Disk I/O largest spike is 6x **smaller** than observed during the 2.7.6 perf checks during the upgrade period
	- Network Traffic had smaller spikes and the largest spike (during the upgrade period) is about 4.7x **less** than observed during the 2.7.6 perf checks
	- Network I/O spikes are much less severe and the largest spike is about 8x smaller than observed during the 2.7.6 perf checks
	- Load Average spikes had much less amplitude on average than observed during the 2.7.6 perf checks
- Overall, many of the performance debugging metrics pre-upgrade varied widely compared to those from the 2.7.6 perf checks
- See full artifacts from the testing here: [Rancher 2.7.7 - 1.26 Perf Checks.zip](https://github.com/rancher/qa-tasks/files/12601408/Rancher.2.7.7.-.1.26.Perf.Checks.zip)

### Pre-Upgrade:
Rancher Cluster:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/2ddb05b6-258e-4785-ac26-6292c43b23c2)

Prometheus:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/3d8659f0-1fc3-4f8b-b3fa-652326a3f27a)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/92d3f7e1-7660-4b99-9827-08db8d5303f5)

Rancher Perf:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/f001c877-dc56-4203-92a4-af5e3518e1d1)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/ebae0162-bf49-4f69-9c76-20be614419bb)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/9a1c9d54-5e84-4522-a9a8-3cd1f0419c59)

### Post-Upgrade:
Rancher Cluster:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/e70504b0-ccf3-4b77-a806-23ffdefabb11)

Prometheus:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/3b85c2ee-d08a-49e0-8f2f-360b8cbc3a45)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/d34dfb32-a84c-4486-aaa2-bf5d989706ec)

Rancher Perf:
![Image](https://github.com/rancher/qa-tasks/assets/85186645/af29414e-157d-4d4d-b38f-cd332d8bcf86)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/8d320b38-4d7e-4c11-8a8b-559faea0ea63)
![Image](https://github.com/rancher/qa-tasks/assets/85186645/09420c71-7176-434a-b420-6952bd436bb7)
