### ISSUE TITLE
[Epic] Add automation/separate repo for rke2 and k3s validations

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#90]
#### Description

It would be very convenient if rke2 and k3s had its own set of validations, probably different than those done through imported clusters in rancher. This could be useful to validate things like kernel params, OS settings, and possibly some basic kubernetes deployments of secrets, deployments, etc. 

#### Tasks

- [ ] Determine what all validations this automation should capture
- [ ] Create separate repo (or directory) with initial code
- [ ] Add validations -- depending on the first task here, this could be large or small. If large, we should probably break this task up into a separate issue in this repo.
  - [ ] Bring the tests over
  - [ ] Turn tests into sonobuoy tests
