### ISSUE TITLE
Public API/kubectl GR

### ISSUE THREAD

**Issue by brudnak** [rancher/qa-tasks#902]
- [x] rancher/qa-tasks#903
- [x] rancher/qa-tasks#904
- [x] rancher/qa-tasks#905
- [x] rancher/qa-tasks#906
- [ ] rancher/qa-tasks#907
