### ISSUE TITLE
Public API/kubectl GRB

### ISSUE THREAD

**Issue by brudnak** [rancher/qa-tasks#908]
- [x] rancher/qa-tasks#909
- [x] rancher/qa-tasks#910
- [x] rancher/qa-tasks#911
- [x] rancher/qa-tasks#912
- [ ] rancher/qa-tasks#913
