### ISSUE TITLE
[EPIC] Automate local/S3 etcd snapshot and restore in downstream clusters

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#986]
# Local Snapshots
## Fresh install
- [x] Create local snapshot and restore etcd only - https://github.com/rancher/qa-tasks/issues/987
- [x] Create local snapshot and restore etcd and K8s version - https://github.com/rancher/qa-tasks/issues/987
- [x] Create local snapshot and restore etcd, K8s version and cluster configuration - https://github.com/rancher/qa-tasks/issues/987
- [x] Create local snapshot, rotate nodes, restore snapshot - https://github.com/rancher/qa-tasks/issues/989
## Upgrade
- [x] Create local snapshot, upgrade K8s version, restore etcd only - https://github.com/rancher/qa-tasks/issues/988
- [x] Create local snapshot, upgrade K8s version, restore etcd and K8s version - https://github.com/rancher/qa-tasks/issues/988
- [x] Create local snapshot, upgrade K8s version, restore etcd, K8s version and cluster configuration - https://github.com/rancher/qa-tasks/issues/988
- [x] Create local snapshot, upgrade K8s version, rotate nodes, restore snapshot - https://github.com/rancher/qa-tasks/issues/989
---
# S3 Snapshots
## Fresh install
- [x] Create S3 snapshot and restore etcd only - https://github.com/rancher/qa-tasks/issues/987
- [x] Create S3 snapshot and restore etcd and K8s version - https://github.com/rancher/qa-tasks/issues/987
- [x] Create S3 snapshot and restore etcd, K8s version and cluster configuration - https://github.com/rancher/qa-tasks/issues/987
- [x] Create S3 snapshot, rotate nodes, restore snapshot - https://github.com/rancher/qa-tasks/issues/989
## Upgrade
- [x] Create S3 snapshot, upgrade K8s version, restore etcd only - https://github.com/rancher/qa-tasks/issues/988
- [x] Create S3 snapshot, upgrade K8s version, restore etcd and K8s version - https://github.com/rancher/qa-tasks/issues/988
- [x] Create S3 snapshot, upgrade K8s version, restore etcd, K8s version and cluster configuration - https://github.com/rancher/qa-tasks/issues/988
- [x] Create S3 snapshot, upgrade K8s version, rotate nodes, restore snapshot - https://github.com/rancher/qa-tasks/issues/989
## MinIO
- [x] Add support for MinIO in the etcd snapshot test suite - https://github.com/rancher/qa-tasks/issues/1013
---
# Disabling/Enabling Automatic Snapshots
- [x] Add option to enable or disable automatic snapshots - https://github.com/rancher/qa-tasks/issues/990
- [x] Add customization to recurring automation schedule - https://github.com/rancher/qa-tasks/issues/992
---
# Recurring Snapshots
- [x] Add customization to the quantity of same snapshot restore - https://github.com/rancher/qa-tasks/issues/993
---
# Node Powered Off
- [x] Add customization to the quantity of powered off etcd nodes when creating a snapshot - https://github.com/rancher/qa-tasks/issues/994
---
# Other
- [x] Allow upgrade strategy to be a customizable input to a user's config - https://github.com/rancher/qa-tasks/issues/1037

**Comment by markusewalker** [comment]
All items in this epic have been covered. Any new test cases that come up will be opened in separate tickets.
